name: Sync to Hugging Face
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HFTOKEN: ${{ secrets.HFTOKEN }}
        run: git push --force https://KAKOOZAMICHAEL:$HFTOKEN@huggingface.co/spaces/KAKOOZAMICHAEL/LATENT-TB-SW-ML-38 main
